FROM ubuntu:latest
#Install Nginx modules
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade && \
    DEBIAN_FRONTEND=noninteractive apt-get -yq install net-tools nginx supervisor

#Configuring Nginx unconfiguration files.
RUN  mkdir -p /var/www/app/code
COPY default /etc/nginx/sites-enabled/
ADD index.html /var/www/app/code

ADD  supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD ["/usr/bin/supervisord"]