apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxhello2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: nginxhello2
        image: kommuri44/nginx2
        ports:
        - name: nginx-port2
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service2
  labels:
    app: nginx-service2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: nginx-port2
    protocol: TCP
    name: nginx2
  selector:
    app: web2
admin@ip-172-20-61-170:~$
